### ISSUE TITLE
Request ever work like as private window

### ISSUE THREAD

**Issue by edutoporoski** [frigus02/RESTer#11]
Every requests work like as private window? For some requests i need the historical cookies, how to disable this?

**Comment by frigus02** [comment]
Hi. This is intentional. The extension is meant to send independent HTTP requests to the server. You can easily add a `Cookie` header to your request if you like.

I will note this as a feature request, though. I'm thinking of something like: automatically add a `Cookie` header to the request, if the previous response contained a `Set-Cookie` header.

It's still a bit of work though, since I will need to build a custom cookie storage. It seems I cannot leverage the default browser behaviour. It is disabled for CORS requests for security reasons. See here if you are interested: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/XMLHttpRequest

**Comment by edutoporoski** [comment]
Thanks, work adding a Cookie in header, but, i think that is a good enhancement include on settings this possibility to set a work with a browser cookie.
Thanks again!

**Comment by frigus02** [comment]
Cookies are fully supported now. See [this comment](https://github.com/frigus02/RESTer/issues/32#issuecomment-345507620) for more info.
