### ISSUE TITLE
Method must be selected from the list, typing is not enough

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#13]
Steps to reproduce: Fill in URL, type method GET, click the submit button twice to send the request

Actual result: Method input is cleared, method `null` is sent in request

Expected result: Method input should keep the typed method and the request should use it. Also the request should be sent on the first click on the submit button.

**Comment by frigus02** [comment]
Hi @maffe. Thanks for reporting. This was a known issue, that should have been fixed in the latest version (1.11.0).

What version of RESTer are you currently running? You can see the version in the browsers addon list or under the about page in RESTer itself (link is small on the buttom left).

**Comment by maffe** [comment]
I’m using 1.11.0 with Firefox 47.0.

**Comment by frigus02** [comment]
I just tried to reproduce it with the exact steps you described in Firefox 47.0.1 and it works perfectly. Meaning it does a GET request.

Could you do me a favor and try the following things:

1. Reload the RESTer page with Ctrl+F5 to make sure this is not a caching issue? If it is, I can make sure this doesn't happen on future updates.
2. Reproduce the error while having the web console open (Ctrl+Shift+K). Maybe it logs some JavaScript errors.

Thanks for helping. This bug is really annoying and I do want to get rid of it.

**Comment by maffe** [comment]
It seems Firefox used an older addon version despite showing 1.11.0 in about:addons. I now have 1.12.0, reloaded the page and the typed method is used. However, it’s still required to click the send button twice when the method input is focused.

**Comment by frigus02** [comment]
Yes, you are right. You need to click twice. Sorry, I overread this in your initial description. So to summarize:

* Bug "method null is sent in request" is fixed.
* Bug "required to click the send button twice" is still open.

I know what the second bug is about and I agree, that is should be fixed. I will see, what I can do.

**Comment by frigus02** [comment]
I just uploaded version 1.12.1, which includes the bugfix. Usually review takes about 1-3 days, after which you should get the update. Please let me know if this works for you.

**Comment by maffe** [comment]
Works perfectly, thank you!
