### ISSUE TITLE
RESTer icon is missing in Firefox (at least in FF47.x)

### ISSUE THREAD

**Issue by DerTomm** [frigus02/RESTer#17]
Today I installed the RESTer Firefox extension and realized that there is no icon shown to start RESTer. In the "customize" view of Firefox RESTer is shown without any icon in the list of available tools. So you cannot drag the tool onto any toolbar.

![screenshot](https://cloud.githubusercontent.com/assets/7753313/17140793/05875610-534a-11e6-8651-5a0a3009d6c2.png)

**Comment by frigus02** [comment]
Well, this is strange. I need to have a closer look at this, because the icon does appear in my local Firefox 47.0.1.

To get a bit more information: Did you try to restart Firefox? And which operating system are you working on?

**Comment by DerTomm** [comment]
Hi Jan,
restarts does not solve the problem. To avoid interferences with other extensions I just disabled all of them and restarted - but the icon is missing nevertheless afterwards.
The OS is Windows 10 64bit.

**Comment by pmdhaussy** [comment]
The icon is present on Firefox 47 Linux version.

**Comment by frigus02** [comment]
Thanks @pmdhaussy. I'm working on Windows 10 64bit as well and the icon is present. This is esepecially strange, since you bascially can't do anything wrong with specifying the icon.

However I found that I can include more icon sizes. Maybe this helps. I will test a bit more in the next days and push out an update this weekend.

**Comment by frigus02** [comment]
@DerTomm Version 1.13.0 is available now. I wasn't able to reproduce the issue, but I did include more icons sizes in the new version. I hope that either this or the update process may fix your issue. Please let me know, whether or not it works for you now.

**Comment by DerTomm** [comment]
Nope - still the same behaviour with the latest release. Are there any ways of debugging?

**Comment by frigus02** [comment]
Hm, can you try the following?
1. Open the Browser Console (_Menu > Developer Tools > Browser Console_ or _Ctrl+Shift+J_)
2. Disable and enable RESTer in about:addons (or maybe even uninstall/install)
3. If no errors were logged, open the customize view while the Browser Console is open.

I hope it logs some kind of errors then.

**Comment by frigus02** [comment]
One more thought. If nothing of this shows errors, could you try to install RESTer in a fresh Firefox profile? To create a new profile, start Firefox with `-P` command line parameter ([more info](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)).

**Comment by DerTomm** [comment]
Here are the console outputs which are created by installing, disabling and enabling RESTer:

```
1470072142876	addons.xpi	WARN	Failed to remove temporary file C:\Users\Thomas\AppData\Local\Temp\tmp-zst.xpi for addon https://addons.mozilla.org/firefox/downloads/file/475163/rester-1.13.0-fx.xpi?src=api: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.remove]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: AddonInstall.prototype.removeTemporaryFile :: line 5389"  data: no] Stack trace: AddonInstall.prototype.removeTemporaryFile()@resource://gre/modules/addons/XPIProvider.jsm:5389 < AddonInstall.prototype.startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6159 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750
Proxy.create and Proxy.createFunction are deprecated, use new Proxy instead environment.js:15:15
Could not read chrome manifest 'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.
Proxy.create and Proxy.createFunction are deprecated, use new Proxy instead environment.js:15:15
CustomizableUI:unable to normalize widget CustomizableUI.jsm:2148
rester:Object { stack: "", 5 weitere… } runner.js:166
rester:Object { stack: "", 5 weitere… } Promise-backend.js:940
```

**Comment by frigus02** [comment]
Hi. Thanks for the logs.

* The first line looks like a permission problem, which could also possibly be caused by an anti virus software. However it's only a warning.
* "Could not read chrome manifest" seems to be completely normal, from what I read.
* The Proxy deprecation messages should be normal as well.
* The last three lines might have something to do with the issue, but it's hard to tell. At least it is not something in the RESTer extension itself, so I can't do something there.

Could you please try to install RESTer in a fresh Firefox profile? This is the last thing I can think of currently.

**Comment by DerTomm** [comment]
Ok, I just tried the new FF profile attempt. And guess what: There it works flawlessly. :-)
Here are the error details I get after clicking "5 weitere...":
![screenshot](https://cloud.githubusercontent.com/assets/7753313/17304157/7bcd8d7e-5824-11e6-8d4e-f5e36dac9ae8.png)

**Comment by frigus02** [comment]
I'm glad that it's at least working in a new profile :-)

Anyway, I looked up existing bug reports regarding the "aId is undefined" message in "CustomizableUI.jsm", but I couldn't find anything helpful. I do not use this file in RESTer, but I assume it's used somewhere under the hoods. This might be a bug in Firefox or your profile is somehow corrupted.

The easiest fix is probably to start with a fresh profile or resetting the existing one. Resetting is possible with the button "Cleanup firefox..."/"Firefox bereinigen..." on the about:support page. As far as I understand it, it will leave your bookmarks and history in place, so it might be a good option.

**Comment by DerTomm** [comment]
I think I found the cause for the problem. RESTer works as long as I do not choose the option "Never remember history" under Preferences -> Privacy - which is my default setting. That's why it works directly after clearing an old profile.
Do you think it is possible to make RESTer work even if this option is choosen?

**Comment by frigus02** [comment]
Hey nice, I can reproduce it with this setting. Good work figuring this out. I'm hope I can make RESTer work with this setting. I will see what I can do.

**Comment by frigus02** [comment]
@DerTomm I finally investigated the issue today and want to give you an update.

Appearently choosing the option *Never remember history* is like having private browsing mode on all the time. Extensions need to specify that they work in private mode, which I didn't do for RESTer. And that's why the icon is missing. This is easy to fix.

However RESTer uses IndexedDB as it's main storage and IndexedDB is currently broken in Firefox in private mode (see [Bug 781982 - IndexedDB does not function in private browsing mode](https://bugzilla.mozilla.org/show_bug.cgi?id=781982)). This means I either need to wait for this bug to be solved or change the storage layer in RESTer.

I have another issue with the IndexedDB when migrating RESTer to WebExtensions (the new Firefox extension framework). I think I will need some time to find a good solution, which fixes both issues. I definitely want to make RESTer work in private mode. But because of these difficulties, I can't give you any timeline.

**Comment by frigus02** [comment]
Hi @DerTomm. Since this morning version 1.14.0 is available, which works in private mode. It took a while but it's finally done. Can you confirm that it works for you now?

**Comment by DerTomm** [comment]
Hi Jan,
yes - looks way better now :-)
The icon did not appear automatically next to the hamburger menu icon this time - but after adding it manually using the Firefox customize feature it is now visible.
Thanks for your efforts!
