### ISSUE TITLE
URL validation is blocking OData query strings

### ISSUE THREAD

**Issue by ashantiel** [frigus02/RESTer#2]
Hi,

string like: http://localhost:11111/Collections?$filter=Property eq true
is normal URL (OData type, spaces are allowed). However, your extension is blocking sending this to server (I mean this block symbol on mouse pointer and inactive "Send" button).

Cheers

**Comment by frigus02** [comment]
Hi @ashantiel, thanks for reporting this. I think it's due to spaces. When you encode them with %20 it lets you do this.

However this is not useable. I think I will remove the URL validation completly. I think it is not necessary. Normally you know how an URL looks like :-)

I will provide an update to the extension in the next few days.

**Comment by frigus02** [comment]
I just uploaded version 1.2.2, which removes the URL validation. It might take a couple of days until it is reviewed, though.

**Comment by ashantiel** [comment]
Great!
Let me test this new version after review so I'd able to "properly" (in the way of software engineering) close this issue :)

Cheers

**Comment by frigus02** [comment]
The new version is available (actually it was reviewed within a few hours). If this fixes your problem, you can close the issue :)

**Comment by ashantiel** [comment]
Yes, new version fixed this problem. Right now it's working very well.

Thanks!
