### ISSUE TITLE
HTTP method drop-down does not appear on click

### ISSUE THREAD

**Issue by denormalizer** [frigus02/RESTer#39]
How to replicate:

* Click empty field for HTTP method
* Drop down appears: POST, GET, PUT, etc
* Select an arbitrary method.
* Backspace, delete HTTP method
* Ensure cursor is still in HTTP method field
* Click empty HTTP method field
* Drop down does not appear

Possibly related to #36

RESTer: v2.5.1

**Comment by frigus02** [comment]
Hi @denormalizer, thanks for your detailed reports. This one actually works as designed. But only because I don't really know how it should behave correctly.

Currently the dropdown only appears when you focus the input field. Once you close the dropdown (by selecting an item or clicking Escape), you can only make it visible again by focusing another element and then going back to the input field.

My thinking was: If you are annoyed by the dropdown and click Escape, it should not reappear without reason.

What would you expect from a dropdown exactly? Do have an example from another tool, where the dropdown works really good?

**Comment by maffe** [comment]
I think the dropdown should appear when using arrow up/down keys, like in the address and search bar in Firefox or editable [JComboBox](http://docs.oracle.com/javase/tutorial/uiswing/components/combobox.html)es.

**Comment by frigus02** [comment]
I like the arrow up/down keys. Seems to work really well. Firefox also starts to show the dropdown again when you continue typing. I might play with this as well.

**Comment by denormalizer** [comment]
@frigus02 I believe for consistency, every time you click on **any** empty field with a defined set of values (eg. HTTP method field) you should be presented with the drop down for those defined values.

The way it works at the moment, if I make a mistake and chose the wrong method (backspace, deleted), I'm no longer presented with the options that are available to me.

@maffe I would be interested to see how the arrow method works. But I believe it might break consistency

**Comment by frigus02** [comment]
@denormalizer Showing the dropdown after clicking on the input field also seems fine for me. I don't see this behavior in the Firefox address bar. But I also think the usecase is different. Especially for the request method, showing the dropdown on click could be a good idea.

As the up and down arrow keys are not used for anything else, I think it should work fine, too. But I will test it to be sure.

**Comment by denormalizer** [comment]
@frigus02 I agree with the different use case. I think the up and down arrow keys would complement the mouse click

**Comment by frigus02** [comment]
I added the improvements in the newest update 3.0.0. For me this feels quite good. Let me know if you find any weird behavior.
