### ISSUE TITLE
Extend containers to max-width:100%;

### ISSUE THREAD

**Issue by acolpan** [frigus02/RESTer#46]
It could be great if you could please extend the max-width of the containers below the "Collection / Title" container to 100%; so that they span the entire view. Please refer to the highlighted area in red in the attached image. Thanks.
![rester](https://user-images.githubusercontent.com/4216057/33584229-0451e3bc-d924-11e7-9937-44983f59826d.png)

**Comment by frigus02** [comment]
Hi @acolpan. Sorry for the late response. I accidentally disabled GitHub notifications and didn't see your issue.

To me this is a tough decision. I can see having the full width being useful. But I also think it can be too wide. I need to think about this one.

**Comment by acolpan** [comment]
You can probably make this optional adding a new menu item named "Full Width" right below the "Full Size" menu item. Please see the attached image.
![full-width](https://user-images.githubusercontent.com/4216057/35392687-49cc36a2-01a8-11e8-9afd-c4be5bdd656e.png)

**Comment by frigus02** [comment]
I'm currently playing with this option and I think I like having more space to view the request. I wonder if all pages (history, settings, environments) should use the full width.

Anyway, I will add an option for the request page for now. It will be on the settings page. I don't want to put it in the dropdown, because it affects the whole page and not just the response body.

**Comment by frigus02** [comment]
Alright. Version 3.6.0 is out (or should be in the next minutes), which has the option on the settings page now.
