### ISSUE TITLE
content-type insted of Content-Type

### ISSUE THREAD

**Issue by the-s-a-m** [frigus02/RESTer#47]
RESTer does sent "content-type" in header insted of "Content-Type"
despite "Content-Type" in configuration.

Thank you and big thanks for your tool 👍

**Comment by frigus02** [comment]
Hi @the-s-a-m. Sorry for the late response. I accidentally disabled GitHub notifications and didn't see your issue.

This issue should have been fixed in version 3.4.0. Could you check, which version you have installed? You can see it in RESTer by clicking on the small "About" link in the bottom left corner. Also: which browser and browser version are you using?

**Comment by the-s-a-m** [comment]
Is fixed thank you :)
