### ISSUE TITLE
Extension permission on Firefox

### ISSUE THREAD

**Issue by aourednik** [frigus02/RESTer#55]
Hi, thank you for developping this ver useful extension.
I have a question: the new version of the Firefox extension makes a new permission request
"Access your data for all websites: The extension can read the content of any web page you visit as well as data you enter into those web pages, such as usernames and passwords." 
Is this necessary? If not, could the the permission request be lowered?

**Comment by frigus02** [comment]
Hi @aourednik, thanks for the question. Unfortunately this permission is necessary. Here's why:

In order to inspect the request and response of HTTP requests, Firefox requires an extension to request permissions to the URL the request is send to. Because RESTer allows you to make requests to every website, it needs permissions to all websites. And this is exactly the "Access your data for all websites" permission you see.

With this permission an extension can inspect and change all requests made to every website you visit. This is scary. RESTer makes sure to only inspect its own requests by limiting the scope to requests in its tab. This way RESTer will never see data from any website you open in any other tab. You can see this in the code here (`tabId` is limited to the current RESTer tab):

https://github.com/frigus02/RESTer/blob/33481e49568b15089aea4d78fee4e787d03d8604/src/site/elements/data/scripts/request.js#L64-L68

I thought about ways to reduce the permission, but could not come up with a good one. For example would be possible to request the permissions on demand. Say you enter the URL `http://example.com` in RESTer. When you click "Send", RESTer could ask for the permission to only the website `http://example.com`. You would get a permission prompt for every request you make in RESTer, though. I don't think this is practical.

If you or anyone else can think of a good way, I would be really happy to change this. I don't like this permission, either.

Thanks again for asking this question. I will put this description in the extension description on AMO and in the README.md here, since I think this will be interesting for others as well.

**Comment by aourednik** [comment]
Many thanks for your answer!

**Comment by frigus02** [comment]
I added the explanation to the readme and to the add-on description on addons.mozilla.org.
