### ISSUE TITLE
Following a redirect changes request method

### ISSUE THREAD

**Issue by megafinz** [frigus02/RESTer#79]
Hi.

Maybe I'm missing some configuration magic, but it appears to me that a request that involves a redirect changes my POST request into a GET request.

In my case I'm POSTing data to `http` endpoint, server responds with `302` and new location with `https` endpoint, and this new location receives GET request instead of the original POST.

I'm using RESTer v3.9.0.

**Comment by frigus02** [comment]
Hi @megafinz, thanks for opening the issue. RESTer has this problem because of limitations of the `fetch` API. You only ever know that a request was redirected (using [`Response.redirected`](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected)), but nothing else. So it can't easily show additional information or stop this from happening.

We should however be able to work around this limitation, because RESTer is a browser extension and has a few more APIs and permissions available.

Regarding the change of the method from POST to GET, see [the MDN article about 302 Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302):

> Even if the specification requires the method (and the body) not to be altered when the redirection is performed, not all user-agents conform here - you can still find this type of bugged software out there. It is therefore recommended to set the `302` code only as a response for `GET` or `HEAD` methods and to use [`307 Temporary Redirect`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) instead, as the method change is explicitly prohibited in that case.

Apparently Firefox does indeed change the method to GET on a 302 response. However in my tests it does not change the request on a 307 response. So I recommend you change your server to respond with 307, if possible.

**Comment by megafinz** [comment]
Hi @frigus02, thanks for a thorough explanation. Not sure I can make it 307, but changing 302 to 301 is possible (https://github.com/containous/traefik/issues/671) and probably should help, will check if this works.

So it turns out that the verb change is a problem of Firefox, but maybe RESTer can provide some verbose logs or something, took me a while to understand why I'm getting 404 for a seemingly valid request.

**Comment by frigus02** [comment]
Oh right, if it's HTTP to HTTPS, that's probably a better idea.

And yes, RESTer should make this obvious. I will look into this.
